name: Build and Push Docker Image

on: 
  push:
    branches:
      -main
      -master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       uses: actions/checkout@v2

      -name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build Docker image
        run: docker build -t totica/2-simpleapp:latest .
      
      - name: Tag Docker image with commit hash
        run: |
          docker tag totica/2-simpleapp:latest totica/2-simpleapp:$(git rev-parse --short HEAD)
          docker tag totica/2-simpleapp:latest totica/2-simpleapp:latest
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push totica/2-simpleapp:$(git rev-parse --short HEAD)
          docker push totica/2-simpleapp:latest
